# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.cache/wt [current_project]
set_property parent.project_path F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/NPC.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/MUX32_3to1.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/RtypeCU.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/MUX3_2to1.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/ALU.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/MUX32_4to1.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/Extend.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/Register.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/MUX5_2to1.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/IR_reg.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/PC.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/MUX32_2to1.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/Memory.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/CU.v
  F:/Vivado/vivadoworkspace/multipleCPU/multipleCPU.srcs/sources_1/new/Main.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
